language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

script:
  - composer update-all
  - composer manifest
  - composer phpunit
  - composer phploc

after_script:
  - composer coveralls
