#
# JBZoo Toolbox - Image
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Image
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Image
#

language: php
os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - JBZOO_COMPOSER_UPDATE_FLAGS="--prefer-lowest --prefer-stable"
    - JBZOO_COMPOSER_UPDATE_FLAGS=""

matrix:
  include:
    - php: 7.2
      env: PHP_VERSION="7.2"
    - php: 7.3
      env: PHP_VERSION="7.3"
    - php: 7.4
      env: PHP_VERSION="7.4"

before_install:
  - sudo apt-get update
  # Re-install php-gd extension to support webp format of images
  - sudo apt-get install -y python-software-properties
  - LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https apt-utils php"$PHP_VERSION"-cli php"$PHP_VERSION"-gd

before_script:
  - composer self-update

script:
  - make update   --no-print-directory
  - make test-all --no-print-directory

after_script:
  - make report-coveralls
